import csv
import sys
import argparse
from pathlib import Path
from typing import Optional, Dict, List

# Add parent path for shared_utils
sys.path.append(str(Path(__file__).parent.parent.parent.parent / "scripts"))
try:
    from shared_utils import Colors, print_header, print_success, print_error, print_warning
except ImportError:
    # Fallback if scripts folder structure is different
    class Colors:
        GREEN = '\033[92m'
        RED = '\033[91m'
        YELLOW = '\033[93m'
        ENDC = '\033[0m'
        BOLD = '\033[1m'
    def print_header(t): print(f"\n{Colors.BOLD}{t}{Colors.ENDC}\n")
    def print_success(t): print(f"{Colors.GREEN}✅ {t}{Colors.ENDC}")
    def print_error(t): print(f"{Colors.RED}❌ {t}{Colors.ENDC}")
    def print_warning(t): print(f"{Colors.YELLOW}⚠️  {t}{Colors.ENDC}")

DATA_DIR = Path(__file__).parent.parent / "data"

def find_row_by_keyword(filepath: Path, keyword: str) -> Optional[Dict]:
    """Search CSV for a row matching keyword in Product Type or Keywords column."""
    if not filepath.exists():
        return None
    
    with open(filepath, mode='r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Check keywords/product type
            searchable = f"{row.get('Product Type', '')} {row.get('Keywords', '')} {row.get('Font Pairing Name', '')} {row.get('Mood/Style Keywords', '')}".lower()
            if keyword.lower() in searchable:
                return row
    return None

def generate_css(color_row: Dict, typo_row: Optional[Dict]) -> str:
    """Generate CSS variables based on design data."""
    css = [
        "/* Generated by Achira Workflow OS - design-tokens.css */",
        ":root {"
    ]
    
    # Colors
    if color_row:
        css.append(f"  /* Palette: {color_row.get('Product Type', 'Custom')} */")
        css.append(f"  --primary: {color_row.get('Primary (Hex)', '#3b82f6')};")
        css.append(f"  --secondary: {color_row.get('Secondary (Hex)', '#64748b')};")
        css.append(f"  --cta: {color_row.get('CTA (Hex)', '#f97316')};")
        css.append(f"  --background: {color_row.get('Background (Hex)', '#ffffff')};")
        css.append(f"  --foreground: {color_row.get('Text (Hex)', '#0f172a')};")
        css.append(f"  --border: {color_row.get('Border (Hex)', '#e2e8f0')};")
        css.append("")

    # Typography
    if typo_row:
        css.append(f"  /* Typography: {typo_row.get('Font Pairing Name', 'Custom')} */")
        css.append(f"  --font-heading: '{typo_row.get('Heading Font', 'Inter')}', sans-serif;")
        css.append(f"  --font-body: '{typo_row.get('Body Font', 'Inter')}', sans-serif;")
        # Extract CSS Import if present
        import_stmt = typo_row.get('CSS Import', '')
        if import_stmt:
            css.insert(1, f"  {import_stmt}")
    
    css.append("}")
    return "\n".join(css)

def main():
    parser = argparse.ArgumentParser(description="Generate design tokens from Achira design data.")
    parser.add_argument("query", help="Keyword to search (e.g. 'saas', 'luxury', 'e-commerce')")
    parser.add_argument("--out", default="design-tokens.css", help="Output file path")
    
    args = parser.parse_args()
    
    print_header(f"✨ Generating Theme for: '{args.query}'")
    
    color_row = find_row_by_keyword(DATA_DIR / "colors.csv", args.query)
    typo_row = find_row_by_keyword(DATA_DIR / "typography.csv", args.query)
    
    if not color_row and not typo_row:
        print_error(f"No design data found for '{args.query}'")
        sys.exit(1)
        
    css_content = generate_css(color_row, typo_row)
    
    with open(args.out, 'w', encoding='utf-8') as f:
        f.write(css_content)
        
    print_success(f"Theme tokens generated at: {args.out}")
    if color_row:
        print(f"  🎨 Color Palette: {color_row['Product Type']}")
    if typo_row:
        print(f"  🔡 Typography: {typo_row['Font Pairing Name']}")

if __name__ == "__main__":
    main()
